# Generated by Django 4.2.7 on 2023-11-23 00:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='home_address',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
