# Generated by Django 4.2.7 on 2023-11-23 01:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_alter_customuser_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsite',
            name='line',
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='point',
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='polygon',
        ),
        migrations.AddField(
            model_name='projectsite',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='site_area',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='site_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='way_to_home',
            field=django.contrib.gis.db.models.fields.LineStringField(default=None, srid=4326),
        ),
    ]
