# Generated by Django 4.2.7 on 2023-11-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_remove_projectsite_line_remove_projectsite_point_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSite',
        ),
    ]
