# Generated by Django 4.1 on 2023-11-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_document_upload_date_projectuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='path',
            new_name='file',
        ),
    ]
