# Generated by Django 4.2.7 on 2023-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_projectsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_project', models.IntegerField(default=0)),
                ('total_user', models.IntegerField(default=0)),
            ],
        ),
    ]
