version: '3'

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    entrypoint: sh /code/docker-entrypoint.sh
  db:
    env_file: .env
    image: postgis/postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: "celery -A project_management_system worker -l INFO"
    depends_on:
      - web
      - redis
    volumes:
      - .:/code
    env_file:
      - .env

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: "celery -A project_management_system beat -l DEBUG"
    depends_on:
      - web
      - redis
    volumes:
      - .:/code
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: