version: '3'

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8000:8000
    entrypoint: sh /code/docker-entrypoint.sh
  db:
    env_file: .env
    image: postgis/postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: